version: '3.8'

services:
  watercolor:
    container_name: watercolor-app
    build:
      context: .
      dockerfile: ./Dockerfile
    image: watercolor-app:latest
    stdin_open: true
    tty: true
    restart: always
    volumes:
      - ~/dev/watercolor:/app
    networks:
      - watercolor-network

networks:
  watercolor-network:
    name: watercolor-network
