name: watercolor

services:
  watercolor:
    container_name: watercolor
    image: watercolor:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8501:8501
    stdin_open: true
    restart: always
    volumes:
      - ~/dev/data:/data
      - ~/dev/watercolor:/app
