name: base
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pycairo
  - streamlit
  - pytest
  - pip
  - pyopengl
  - pathlib
  - pip
  - pip:
      - pymixbox
      - opencv-python-headless