name: base
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pycairo
  - streamlit
  - pytest
  - pyopengl
  - pathlib
  - scikit-learn
  - numba
  - tqdm  # Added tqdm for progress bars
  - pillow # Added Pillow for image handling in simulation_main
  - pip
  - pip:
      - pymixbox
      - opencv-python-headless